apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: openshift-rbac
  name: openshift-rbac
  selfLink: /apis/apps.openshift.io/v1/namespaces/rbac-lab/deploymentconfigs/openshift-rbac
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: openshift-rbac
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-rbac
        deploymentconfig: openshift-rbac
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/rbac-lab/openshift-rbac@sha256:6b60dc1174918d90b4d727720dac79469d3072e56b28796e6aed361221f28e0e
        imagePullPolicy: Always
        name: openshift-rbac
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-rbac
      from:
        kind: ImageStreamTag
        name: openshift-rbac:latest
        namespace: rbac-lab
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
