apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: openshift-rbac
    build: openshift-rbac
  name: openshift-rbac
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift-rbac
